import os
from dotenv import load_dotenv

load_dotenv()

# API KEYS
KUCOIN_API_KEY = os.getenv("KUCOIN_API_KEY")
KUCOIN_SECRET = os.getenv("KUCOIN_SECRET")
KUCOIN_PASSPHRASE = os.getenv("KUCOIN_PASSPHRASE")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# DEFAULTS FOR DB INITIALIZATION
DEFAULT_SYMBOLS = [
    'BTC/USDT:USDT', 'ETH/USDT:USDT', 'BNB/USDT:USDT', 'SOL/USDT:USDT', 'XRP/USDT:USDT',
    'AVAX/USDT:USDT', 'TRX/USDT:USDT', 'TON/USDT:USDT', 'NEAR/USDT:USDT', 'SUI/USDT:USDT',
    'ATOM/USDT:USDT', 'LTC/USDT:USDT', 'DOGE/USDT:USDT', 'XMR/USDT:USDT', 'ZEC/USDT:USDT',
    'LINK/USDT:USDT', 'UNI/USDT:USDT', 'CRO/USDT:USDT', 'FET/USDT:USDT', 'ANKR/USDT:USDT',
    'CHR/USDT:USDT', 'PEPE/USDT:USDT', 'GAIB/USDT:USDT', 'DGRAM/USDT:USDT', 'PLANCK/USDT:USDT',
    'TNSR/USDT:USDT'
]

DEFAULT_LEVERAGE = 10
DEFAULT_BASE_ORDER_SIZE = 2
DEFAULT_MAX_POSITIONS = 10

DEFAULT_STRATEGIST_INTERVAL = 30
DEFAULT_EXECUTION_INTERVAL = 5

DEFAULT_AI_MODEL = 'gemini-2.0-flash-lite'

DEFAULT_ORDER_IMBALANCE_THR = 1.01
DEFAULT_MIN_VOLUME_24H = 10000

DEFAULT_ATR_PERIOD = 14
DEFAULT_ATR_MULTIPLIER_SL = 1.5
DEFAULT_ATR_MULTIPLIER_TP = 2.0
